/**
 * Digivolution chain data for all available Digimon sprites.
 * Only includes evolution paths where both source and target sprites exist.
 * Names are lowercase and match GIF filenames (without .gif extension).
 */

// Maps each Digimon to an array of possible digivolutions (next stage evolutions).
const DIGIVOLUTION_CHAINS = {
  // ========== BABY (In-Training) → CHILD (Rookie) ==========
  'botamon':     ['koromon'],
  'koromon':     ['agumon', 'dotagumon', 'toyagumon', 'blackagumon', 'guilmon'],
  'poyomon':     ['tokomon'],
  'tokomon':     ['patamon', 'plotmon'],
  'tsunomon':    ['gabumon', 'goblimon', 'bearmon'],
  'tanemon':     ['palmon', 'floramon', 'alraumon', 'mushmon'],
  'budmon':      ['palmon', 'floramon', 'alraumon', 'raramon'],
  'chibomon':    ['v-mon'],
  'chicchimon':  ['v-mon'],
  'chocomon':    ['lopmon', 'terriermon'],
  'gumymon':     ['terriermon'],
  'gigimon':     ['guilmon'],
  'dorimon':     ['dorumon'],
  'kapurimon':   ['kotemon', 'hagurumon', 'kokuwamon', 'kudamon'],
  'minomon':     ['wormmon'],
  'kuramon':     ['keramon', 'tsukaimon'],
  'tsumemon':    ['keramon', 'impmon'],
  'pagumon':     ['gabumon', 'impmon', 'picodevimon', 'dracmon', 'tsukaimon'],
  'wanyamon':    ['gaomon'],
  'moonmon':     ['lunamon'],
  'sunmon':      ['coronamon'],
  'puttimon':    ['falcomon', 'hawkmon'],
  'calumon':     [],

  // ========== CHILD (Rookie) → ADULT (Champion) ==========
  'agumon':      ['greymon', 'geogreymon', 'tyranomon', 'centarumon', 'monochromon', 'numemon', 'sukamon'],
  'blackagumon': ['greymon', 'darktyrannomon', 'darklizardmon', 'monochromon'],
  'dotagumon':   ['greymon', 'tyranomon'],
  'toyagumon':   ['guardromon', 'starmon', 'tankmon', 'mechanorimon', 'numemon'],
  'toyagumonblack': ['guardromon', 'tankmon', 'mechanorimon'],
  'yukiagumon':  ['frigimon', 'hyogamon', 'mojyamon', 'icedevimon'],
  'gabumon':     ['garurumon', 'drimogemon', 'ogremon', 'numemon', 'monochromon'],
  'patamon':     ['angemon', 'unimon', 'bakemon', 'numemon'],
  'plotmon':     ['tailmon', 'seasarmon', 'sorcerymon'],
  'biyomon':     ['birdramon', 'saberdramon', 'akatorimon', 'kiwimon', 'airdramon'],
  'palmon':      ['togemon', 'woodmon', 'veggiemon', 'numemon', 'sunflowmon'],
  'tentomon':    ['kabuterimon', 'kuwagamon', 'flymon', 'snimon', 'thundermon'],
  'gomamon':     ['ikkakumon', 'coelamon', 'gesomon', 'dolphmon', 'seadramon', 'shellmon'],
  'guilmon':     ['growlmon', 'tyranomon', 'greymon', 'monochromon'],
  'terriermon':  ['galgomon', 'frigimon', 'unimon', 'starmon'],
  'renamon':     ['kyubimon', 'firamon', 'leomon'],
  'v-mon':       ['xv-mon', 'v-dramon', 'greymon', 'leomon'],
  'wormmon':     ['stingmon', 'dokugumon', 'flymon', 'kunemon'],
  'impmon':      ['devimon', 'evilmon', 'ogremon', 'sangloupmon', 'bakemon'],
  'hawkmon':     ['aquilamon', 'airdramon', 'birdramon', 'saberdramon'],
  'armademon':   ['ankylomon', 'tortomon', 'golemon', 'monochromon'],
  'monodramon':  ['raptordramon', 'devidramon', 'airdramon', 'angemon'],
  'dorumon':     ['dorugamon', 'raptordramon', 'greymon'],
  'gaomon':      ['gaogamon', 'grizzmon', 'leomon'],
  'falcomon':    ['peckmon', 'diatrymon', 'kiwimon', 'birdramon', 'saberdramon'],
  'lunamon':     ['lekismon', 'sorcerymon'],
  'coronamon':   ['firamon', 'leomon', 'greymon'],
  'keramon':     ['chrysalimon', 'devidramon', 'raremon'],
  'lopmon':      ['wendimon', 'apemon', 'bakemon'],
  'betamon':     ['seadramon', 'octomon', 'gesomon', 'shellmon', 'coelamon'],
  'floramon':    ['togemon', 'sunflowmon', 'woodmon', 'veggiemon', 'kiwimon'],
  'alraumon':    ['togemon', 'woodmon', 'redveggiemon', 'sunflowmon'],
  'candmon':     ['wizarmon', 'starmon', 'clockmon'],
  'kotemon':     ['dinohumon', 'musyamon', 'igamon', 'starmon', 'leomon'],
  'kudamon':     ['leppamon', 'seasarmon', 'starmon'],
  'kokuwamon':   ['guardromon', 'thundermon', 'tankmon', 'kuwagamon'],
  'hagurumon':   ['guardromon', 'clockmon', 'tankmon', 'mechanorimon', 'starmon'],
  'goblimon':    ['ogremon', 'fugamon', 'apemon', 'nanimon'],
  'snowgoblimon':['frigimon', 'hyogamon', 'icedevimon', 'mojyamon'],
  'mushmon':     ['woodmon', 'veggiemon', 'redveggiemon'],
  'kunemon':     ['flymon', 'snimon', 'dokugumon', 'kuwagamon'],
  'dokunemon':   ['dokugumon', 'flymon', 'snimon', 'weedmon'],
  'dracmon':     ['sangloupmon', 'evilmon', 'devimon', 'devidramon'],
  'picodevimon': ['devimon', 'bakemon', 'evilmon', 'wizarmon', 'sorcerymon'],
  'tsukaimon':   ['devidramon', 'bakemon', 'evilmon', 'devimon'],
  'gizamon':     ['gesomon', 'octomon', 'ebidramon', 'seadramon'],
  'ganimon':     ['ebidramon', 'gesomon', 'shellmon', 'coelamon'],
  'shakomon':    ['gesomon', 'octomon', 'shellmon', 'coelamon'],
  'otamamon':    ['gekomon', 'seadramon', 'numemon'],
  'penmon':      ['frigimon', 'icedevimon', 'dolphmon', 'seadramon'],
  'bearmon':     ['grizzmon', 'apemon', 'leomon'],
  'muchomon':    ['akatorimon', 'kiwimon', 'birdramon', 'saberdramon'],
  'gotsumon':    ['golemon', 'icemon', 'monochromon', 'starmon'],
  'shamamon':    ['apemon', 'fugamon', 'ogremon', 'centarumon'],
  'solarmon':    ['starmon', 'guardromon', 'clockmon', 'thundermon'],
  'kamemon':     ['gwappamon', 'dolphmon', 'seadramon', 'shellmon'],
  'raramon':     ['sunflowmon', 'togemon', 'woodmon', 'veggiemon'],
  'bakumon':     ['wizarmon', 'sorcerymon', 'clockmon', 'bakemon'],
  'pawnchessmonblack': ['knightchessmonblack'],
  'pawnchessmonwhite': ['knightchessmonwhite'],

  // ========== ADULT (Champion) → PERFECT (Ultimate) ==========
  'greymon':         ['metalgreymon', 'skullgreymon', 'rizegreymon', 'vermilimon', 'mamemon'],
  'geogreymon':      ['rizegreymon', 'metalgreymon', 'skullgreymon'],
  'garurumon':       ['weregarurumon', 'weregarurumonblack', 'megaseadramon', 'pandamon'],
  'angemon':         ['holyangemon', 'vamdemon', 'qilinmon'],
  'birdramon':       ['garudamon', 'arachnemon'],
  'togemon':         ['lilymon', 'blossomon', 'deramon'],
  'kabuterimon':     ['megakabuterimonblue', 'okuwamon'],
  'ikkakumon':       ['zudomon', 'mammothmon', 'whamon'],
  'growlmon':        ['wargrowlmon', 'megadramon', 'gigadramon'],
  'galgomon':        ['rapidmon', 'pandamon'],
  'kyubimon':        ['taomon', 'karatenmon', 'kyukimon'],
  'xv-mon':          ['paildramon', 'aeroveedramon'],
  'stingmon':        ['dinobeemon', 'okuwamon'],
  'aquilamon':       ['silphymon', 'garudamon', 'karatenmon'],
  'ankylomon':       ['shakkoumon', 'brachiomon'],
  'raptordramon':    ['cyberdramon', 'megadramon', 'gigadramon'],
  'dorugamon':       ['dorugreymon', 'gigadramon', 'megadramon'],
  'gaogamon':        ['machgaogamon', 'weregarurumon'],
  'peckmon':         ['yatagaramon', 'karatenmon'],
  'lekismon':        ['crescemon', 'pipismon'],
  'firamon':         ['flaremon', 'lynxmon'],
  'chrysalimon':     ['infermon', 'okuwamon'],
  'tailmon':         ['angewomon', 'ladydevimon', 'silphymon', 'nefertimon'],
  'v-dramon':        ['aeroveedramon', 'metalgreymon'],
  'leomon':          ['grappleomon', 'mamemon', 'monzaemon'],
  'devimon':         ['vamdemon', 'ladydevimon', 'phantomon', 'skullgreymon'],
  'ogremon':         ['etemon', 'gigadramon'],
  'tyranomon':       ['metaltyrannomon', 'megadramon', 'mamemon', 'triceramon'],
  'darktyrannomon':  ['metaltyrannomon', 'xtyrannomon', 'skullgreymon'],
  'seadramon':       ['megaseadramon', 'whamon', 'dragomon', 'scorpiomon'],
  'shellmon':        ['megaseadramon', 'whamon', 'scorpiomon'],
  'gesomon':         ['dragomon', 'marinedevimon', 'divermon'],
  'coelamon':        ['whamon', 'dragomon', 'divermon', 'scorpiomon'],
  'dolphmon':        ['whamon', 'seahomon', 'divermon'],
  'octomon':         ['dragomon', 'marinedevimon', 'divermon'],
  'ebidramon':       ['scorpiomon', 'dragomon', 'marinedevimon'],
  'monochromon':     ['triceramon', 'vermilimon', 'metaltyrannomon'],
  'numemon':         ['monzaemon', 'etemon', 'garbagemon'],
  'sukamon':         ['etemon', 'garbagemon', 'vademon'],
  'drimogemon':      ['andromon', 'gigadramon', 'giromon'],
  'starmon':         ['superstarmon', 'meteormon'],
  'guardromon':      ['andromon', 'knightmon', 'nanomon', 'giromon'],
  'centarumon':      ['andromon', 'knightmon', 'qilinmon'],
  'bluemeramon':     ['flaremon'],
  'darklizardmon':   ['metaltyrannomon', 'gigadramon', 'xtyrannomon'],
  'devidramon':      ['gigadramon', 'megadramon', 'cyberdramon'],
  'wizarmon':        ['phantomon', 'taomon', 'vamdemon'],
  'sorcerymon':      ['phantomon', 'taomon', 'holyangemon'],
  'kuwagamon':       ['okuwamon', 'dinobeemon'],
  'flymon':          ['okuwamon', 'dinobeemon'],
  'snimon':          ['okuwamon', 'dinobeemon'],
  'dokugumon':       ['arachnemon', 'okuwamon'],
  'bakemon':         ['phantomon', 'vamdemon', 'ponchomon'],
  'frigimon':        ['mammothmon', 'monzaemon', 'pandamon'],
  'mojyamon':        ['mammothmon', 'pandamon'],
  'hyogamon':        ['mammothmon'],
  'icedevimon':      ['vamdemon', 'ladydevimon', 'phantomon'],
  'woodmon':         ['cherrymon', 'blossomon', 'deramon'],
  'veggiemon':       ['blossomon', 'garbagemon', 'deramon'],
  'redveggiemon':    ['blossomon', 'garbagemon', 'deramon'],
  'weedmon':         ['blossomon', 'cherrymon'],
  'sunflowmon':      ['lilamon', 'lilymon', 'blossomon'],
  'saberdramon':     ['garudamon', 'karatenmon', 'yatagaramon'],
  'akatorimon':      ['garudamon', 'deramon', 'parrotmon'],
  'kiwimon':         ['deramon', 'parrotmon', 'garudamon'],
  'wendimon':        ['antiramon', 'blackrapidmon'],
  'grizzmon':        ['grappleomon', 'pandamon', 'mammothmon'],
  'apemon':          ['mammothmon', 'grappleomon', 'etemon'],
  'fugamon':         ['etemon', 'grappleomon'],
  'nanimon':         ['etemon', 'garbagemon'],
  'musyamon':        ['karatenmon', 'knightmon', 'volcamon'],
  'igamon':          ['karatenmon', 'knightmon', 'matadormon'],
  'dinohumon':       ['knightmon', 'dinobeemon', 'volcamon'],
  'leppamon':        ['qilinmon', 'taomon'],
  'seasarmon':       ['seahomon', 'holyangemon'],
  'clockmon':        ['nanomon', 'andromon', 'giromon'],
  'tankmon':         ['andromon', 'gigadramon', 'nanomon'],
  'mechanorimon':    ['andromon', 'nanomon', 'giromon', 'metaltyrannomon'],
  'thundermon':      ['mamemon', 'andromon', 'giromon'],
  'sangloupmon':     ['matadormon', 'ladydevimon', 'vamdemon'],
  'evilmon':         ['vamdemon', 'ladydevimon', 'phantomon'],
  'golemon':         ['mammothmon', 'kenkimon', 'volcamon'],
  'icemon':          ['mammothmon', 'meteormon'],
  'tortomon':        ['brachiomon', 'triceramon'],
  'gwappamon':       ['shaujingmon', 'divermon', 'seahomon'],
  'airdramon':       ['megadramon', 'gigadramon', 'aeroveedramon'],
  'unimon':          ['mammothmon', 'holyangemon', 'piximon'],
  'minotarumon':     ['volcamon', 'kenkimon'],
  'raremon':         ['garbagemon', 'phantomon', 'marinedevimon'],
  'gekomon':         ['shogungekomon', 'dragomon', 'whamon'],
  'diatrymon':       ['yatagaramon', 'garudamon'],
  'hookmon':         ['divermon', 'seahomon'],
  'kokatorimon':     ['deramon', 'parrotmon'],
  'roachmon':        ['garbagemon', 'okuwamon'],
  'knightchessmonblack': ['bishopchessmon'],
  'knightchessmonwhite': ['bishopchessmon'],
  'kougamon':        ['karatenmon', 'kyukimon', 'matadormon'],

  // ========== PERFECT (Ultimate) → ULTIMATE (Mega) ==========
  'metalgreymon':    ['wargreymon', 'blackwargreymon', 'machinedramon', 'gaiomon'],
  'rizegreymon':     ['shinegreymon', 'wargreymon', 'blackwargreymon'],
  'skullgreymon':    ['machinedramon', 'blackwargreymon', 'skullmammon'],
  'weregarurumon':   ['metalgarurumon', 'baihumon'],
  'weregarurumonblack': ['metalgarurumon', 'blacksaintgalgomon'],
  'holyangemon':     ['seraphimon', 'slashangemon', 'ophanimon', 'goldramon'],
  'garudamon':       ['phoenixmon', 'varodurumon', 'gryphonmon'],
  'lilymon':         ['rosemon', 'lotusmon', 'gryphonmon'],
  'lilamon':         ['rosemon', 'lotusmon', 'rosemonburst'],
  'megakabuterimonblue': ['herculeskabuterimon'],
  'zudomon':         ['vikemon', 'plesiomon', 'marineangemon'],
  'wargrowlmon':     ['dukemon', 'megidramon'],
  'blackwargrowlmon': ['chaosdukemon', 'megidramon'],
  'rapidmon':        ['saintgalgomon', 'cherubimon'],
  'blackrapidmon':   ['blacksaintgalgomon', 'cherubimonvirus'],
  'taomon':          ['sakuyamon', 'kuzuhamon'],
  'paildramon':      ['imperialdramon', 'imperialdramonfighter'],
  'dinobeemon':      ['grankuwagamon', 'herculeskabuterimon'],
  'silphymon':       ['valkyrimon', 'phoenixmon', 'ophanimon'],
  'shakkoumon':      ['vikemon', 'slashangemon'],
  'cyberdramon':     ['justimon', 'darkdramon'],
  'dorugreymon':     ['dorugoramon', 'alphamon'],
  'machgaogamon':    ['miragegaogamon', 'miragegaogamonburst'],
  'yatagaramon':     ['ravemon', 'ravemonburst'],
  'crescemon':       ['dianamon', 'lilithmon'],
  'flaremon':        ['apollomon', 'baihumon', 'zhuqiaomon'],
  'infermon':        ['diaboromon', 'armageddemon'],
  'angewomon':       ['ophanimon', 'magnadramon', 'lotusmon', 'rosemon'],
  'ladydevimon':     ['lilithmon', 'ophanimoncore', 'piedmon'],
  'vamdemon':        ['belialvamdemon', 'venommyotismon', 'piedmon'],
  'andromon':        ['hiandromon', 'machinedramon', 'cannondramon'],
  'etemon':          ['metaletemon', 'princemamemon'],
  'mamemon':         ['princemamemon', 'metalmamemon'],
  'metalmamemon':    ['princemamemon'],
  'megaseadramon':   ['metalseadramon', 'gigaseadramon', 'plesiomon'],
  'marinedevimon':    ['pukumon', 'leviamon', 'daemon'],
  'whamon':          ['plesiomon', 'neptunmon', 'marineangemon'],
  'mammothmon':      ['skullmammon', 'vikemon'],
  'metaltyrannomon': ['machinedramon', 'darkdramon', 'cannondramon'],
  'gigadramon':      ['machinedramon', 'cannondramon', 'darkdramon'],
  'megadramon':      ['machinedramon', 'cannondramon', 'darkdramon'],
  'phantomon':       ['piedmon', 'daemon', 'pharaohmon'],
  'monzaemon':       ['princemamemon', 'puppetmon', 'babamon'],
  'piximon':         ['jijimon', 'babamon', 'marineangemon'],
  'grappleomon':     ['bantyoleomon', 'saberleomon'],
  'knightmon':       ['duftmon', 'sleipmon', 'alphamon'],
  'triceramon':      ['spinomon', 'cannondramon'],
  'brachiomon':      ['cannondramon', 'spinomon'],
  'cherrymon':       ['puppetmon', 'gryphonmon'],
  'blossomon':       ['rosemon', 'lotusmon', 'gryphonmon'],
  'deramon':         ['gryphonmon', 'phoenixmon', 'eaglemon'],
  'parrotmon':       ['eaglemon', 'phoenixmon', 'gryphonmon'],
  'garbagemon':      ['metaletemon', 'pukumon', 'devitamamon'],
  'okuwamon':        ['grankuwagamon', 'herculeskabuterimon'],
  'aeroveedramon':   ['imperialdramon', 'goldramon'],
  'digitamamon':     ['devitamamon', 'pharaohmon'],
  'superstarmon':    ['justimon', 'minervamon'],
  'meteormon':       ['ebemon', 'alphamon'],
  'nanomon':         ['hiandromon', 'machinedramon', 'ebemon'],
  'giromon':         ['hiandromon', 'ebemon', 'machinedramon'],
  'dragomon':        ['leviamon', 'neptunmon', 'pukumon'],
  'scorpiomon':      ['pukumon', 'gigaseadramon'],
  'divermon':        ['plesiomon', 'marineangemon', 'neptunmon'],
  'seahomon':        ['marineangemon', 'neptunmon', 'plesiomon'],
  'shogungekomon':   ['plesiomon', 'leviamon'],
  'qilinmon':        ['sleipmon', 'goldramon'],
  'antiramon':       ['cherubimon', 'cherubimonvirus'],
  'volcamon':        ['boltmon', 'minervamon'],
  'kenkimon':        ['boltmon', 'cannondramon'],
  'karatenmon':      ['ravemon', 'zanbamon'],
  'kyukimon':        ['kuzuhamon', 'sakuyamon'],
  'matadormon':      ['piedmon', 'grandracmon'],
  'pandamon':        ['bantyoleomon', 'saberleomon'],
  'bishopchessmon':  ['rookchessmon', 'kingchessmon', 'queenchessmon'],
  'rookchessmon':    ['kingchessmon', 'queenchessmon'],
  'magnamon':        ['imperialdramon', 'imperialdramonfighter'],
  'vermilimon':      ['spinomon', 'cannondramon'],
  'xtyrannomon':     ['machinedramon', 'darkdramon'],
  'kongoumon':       ['boltmon', 'minervamon'],
  'sinduramon':      ['zhuqiaomon', 'phoenixmon'],
  'vajramon':        ['baihumon', 'xuanwumon'],
  'bigmamemon':      ['princemamemon'],
  'arachnemon':      ['parasimon', 'lilithmon'],
  'flamedramon':     ['imperialdramon', 'magnamon'],
  'shadramon':       ['eaglemon'],
  'shurimon':        ['zanbamon', 'ravemon'],
  'allomon':         ['spinomon', 'cannondramon'],
  'mametyramon':     ['spinomon', 'cannondramon'],
  'pipismon':        ['dianamon', 'lotusmon'],
  'lynxmon':         ['apollomon', 'baihumon'],
  'shaujingmon':     ['neptunmon', 'vikemon'],
  'ponchomon':       ['piedmon', 'puppetmon'],
  'mummymon':        ['pharaohmon'],
  'prariemon':       ['bantyoleomon'],
  'tekkamon':        ['boltmon', 'machinedramon'],
  'owlmon':          ['valkyrimon', 'ravemon'],
  'kabukimon':       ['gryphonmon', 'cherrymon'],

  // ========== ADDITIONS folder Digimon ==========
  'lucemon':         ['lucemonfdm'],
  'gaossmon':        ['greymonxw'],
  'greymonxw':       [],
  'cerberumon':      ['anubismon'],
  'bluemeramon':     ['boltmon'],
  'dondokomon':      [],
  'bommon':          ['budmon', 'dorimon'],
  'bastemon':        ['lilithmon', 'minervamon'],
  'blastmon':        [],
  'tactimon':        [],
  'skullscorpiomon': ['grandracmon'],
  'chaosdramon':     [],
  'aegisdramon':     [],
  'daipenmon':       [],
  'nefertimon':      ['angewomon', 'ophanimon'],
  'madleomon':       ['bantyoleomon', 'saberleomon'],
  'shoutmonb':       [],
  'beelzemonxros':   [],

  // ========== MEGA with further evolutions ==========
  'dukemon':             ['dukemoncm'],
  'chaosdukemon':        ['chaosdukemoncore'],
  'shinegreymon':        ['shinegreymonburst', 'shinegreymonruin'],
  'miragegaogamon':      ['miragegaogamonburst'],
  'ravemon':             ['ravemonburst'],
  'rosemon':             ['rosemonburst'],
  'beelzebumon':         ['beelzebumonblaster'],
  'imperialdramon':      ['imperialdramonfighter'],
  'imperialdramonfighter': ['imperialdramonpaladin'],
  'grimmon':             ['exogrimmon', 'chaosgrimmon'],
  'chaosgrimmon':        ['exogrimmon'],
  'milleniummon':        ['moonmilleniummon'],
  'moonmilleniummon':    ['zeedmillenniummon'],
  'diaboromon':          ['armageddemon'],
  'chronomon':           ['chronomondm'],
  'deathmon':            ['deathmonblack'],
  'omegamon':            [],

  // ========== MEGA with no further standard evolutions ==========
  'wargreymon':          ['omegamon'],
  'metalgarurumon':      ['omegamon'],
  'blackwargreymon':     [],
  'seraphimon':          ['susanoomon'],
  'ophanimon':           [],
  'ophanimoncore':       [],
  'magnadramon':         [],
  'phoenixmon':          [],
  'herculeskabuterimon': [],
  'vikemon':             [],
  'saintgalgomon':       [],
  'blacksaintgalgomon':  [],
  'sakuyamon':           [],
  'kuzuhamon':           [],
  'grankuwagamon':       [],
  'justimon':            [],
  'dorugoramon':         ['alphamon'],
  'alphamon':            [],
  'apollomon':           [],
  'dianamon':            [],
  'plesiomon':           [],
  'marineangemon':       [],
  'saberleomon':         [],
  'bantyoleomon':        [],
  'piedmon':             [],
  'puppetmon':           [],
  'machinedramon':       [],
  'metalseadramon':      [],
  'metaletemon':         [],
  'princemamemon':       [],
  'hiandromon':          [],
  'boltmon':             [],
  'goldramon':           [],
  'sleipmon':            [],
  'duftmon':             [],
  'darkdramon':          [],
  'cannondramon':        [],
  'spinomon':            [],
  'pukumon':             [],
  'leviamon':            [],
  'neptunmon':           [],
  'gigaseadramon':       [],
  'ebemon':              [],
  'valkyrimon':          [],
  'varodurumon':         [],
  'gryphonmon':          [],
  'lotusmon':            [],
  'eaglemon':            [],
  'minervamon':          [],
  'zanbamon':            [],
  'pharaohmon':          [],
  'grandracmon':         [],
  'daemon':              [],
  'creepymon':           [],
  'lilithmon':           [],
  'barbamon':            [],
  'belphemon':           [],
  'cherubimon':          [],
  'cherubimonvirus':     [],
  'belialvamdemon':      [],
  'venommyotismon':      [],
  'devitamamon':         [],
  'megidramon':          [],
  'armageddemon':        [],
  'baihumon':            [],
  'zhuqiaomon':          [],
  'xuanwumon':           [],
  'quinglongmon':        [],
  'babamon':             [],
  'jijimon':             [],
  'parasimon':           [],
  'skullmammon':         [],
  'skullbarukimon':      [],
  'gaiomon':             [],
  'chaosmon':            [],
  'susanoomon':          [],
  'anubismon':           [],
  'lampmon':             [],
  'apocalymon':          [],
  'slashangemon':        [],
  'granlocomon':         [],
  'lucemonfdm':          ['galfmon'],
  'galfmon':             [],
  'kingchessmon':        [],
  'queenchessmon':       [],
  'merukimon':           [],
  'argomonultimate':     [],
  'argomonperfect':      ['argomonultimate'],
  'jumbogamemon':        [],
};

// Maps each Digimon to its evolution stage based on folder location.
// Folder mapping: Baby → Baby, Child → Rookie, Adult → Champion, Perfect → Ultimate, Ultimate → Mega
const STAGE_ORDER = {
  // Baby (In-Training)
  'botamon': 'Baby',
  'budmon': 'Baby',
  'calumon': 'Baby',
  'chibomon': 'Baby',
  'chicchimon': 'Baby',
  'chocomon': 'Baby',
  'dorimon': 'Baby',
  'gigimon': 'Baby',
  'gumymon': 'Baby',
  'kapurimon': 'Baby',
  'koromon': 'Baby',
  'kuramon': 'Baby',
  'minomon': 'Baby',
  'moonmon': 'Baby',
  'pagumon': 'Baby',
  'poyomon': 'Baby',
  'puttimon': 'Baby',
  'sunmon': 'Baby',
  'tanemon': 'Baby',
  'tokomon': 'Baby',
  'tsumemon': 'Baby',
  'tsunomon': 'Baby',
  'wanyamon': 'Baby',

  // Rookie (Child)
  'agumon': 'Rookie',
  'alraumon': 'Rookie',
  'armademon': 'Rookie',
  'bakumon': 'Rookie',
  'bearmon': 'Rookie',
  'betamon': 'Rookie',
  'biyomon': 'Rookie',
  'blackagumon': 'Rookie',
  'candmon': 'Rookie',
  'coronamon': 'Rookie',
  'dokunemon': 'Rookie',
  'dorumon': 'Rookie',
  'dotagumon': 'Rookie',
  'dotfalcomon': 'Rookie',
  'dracmon': 'Rookie',
  'falcomon': 'Rookie',
  'floramon': 'Rookie',
  'gabumon': 'Rookie',
  'ganimon': 'Rookie',
  'gaomon': 'Rookie',
  'gizamon': 'Rookie',
  'goblimon': 'Rookie',
  'gomamon': 'Rookie',
  'gotsumon': 'Rookie',
  'guilmon': 'Rookie',
  'hagurumon': 'Rookie',
  'hawkmon': 'Rookie',
  'impmon': 'Rookie',
  'kamemon': 'Rookie',
  'keramon': 'Rookie',
  'kokuwamon': 'Rookie',
  'kotemon': 'Rookie',
  'kudamon': 'Rookie',
  'kunemon': 'Rookie',
  'lopmon': 'Rookie',
  'lunamon': 'Rookie',
  'monodramon': 'Rookie',
  'muchomon': 'Rookie',
  'mushmon': 'Rookie',
  'otamamon': 'Rookie',
  'palmon': 'Rookie',
  'patamon': 'Rookie',
  'pawnchessmonblack': 'Rookie',
  'pawnchessmonwhite': 'Rookie',
  'penmon': 'Rookie',
  'picodevimon': 'Rookie',
  'plotmon': 'Rookie',
  'raramon': 'Rookie',
  'renamon': 'Rookie',
  'shakomon': 'Rookie',
  'shamamon': 'Rookie',
  'snowgoblimon': 'Rookie',
  'solarmon': 'Rookie',
  'tentomon': 'Rookie',
  'terriermon': 'Rookie',
  'toyagumon': 'Rookie',
  'toyagumonblack': 'Rookie',
  'tsukaimon': 'Rookie',
  'v-mon': 'Rookie',
  'wormmon': 'Rookie',
  'yukiagumon': 'Rookie',

  // Champion (Adult)
  'airdramon': 'Champion',
  'akatorimon': 'Champion',
  'angemon': 'Champion',
  'ankylomon': 'Champion',
  'apemon': 'Champion',
  'aquilamon': 'Champion',
  'bakemon': 'Champion',
  'birdramon': 'Champion',
  'bombernanimon': 'Champion',
  'centarumon': 'Champion',
  'chrysalimon': 'Champion',
  'clockmon': 'Champion',
  'coelamon': 'Champion',
  'darklizardmon': 'Champion',
  'darktyrannomon': 'Champion',
  'deputymon': 'Champion',
  'devidramon': 'Champion',
  'devimon': 'Champion',
  'diatrymon': 'Champion',
  'dinohumon': 'Champion',
  'dokugumon': 'Champion',
  'dolphmon': 'Champion',
  'dorugamon': 'Champion',
  'drimogemon': 'Champion',
  'ebidramon': 'Champion',
  'evilmon': 'Champion',
  'firamon': 'Champion',
  'flarelizardmon': 'Champion',
  'flymon': 'Champion',
  'frigimon': 'Champion',
  'fugamon': 'Champion',
  'galgomon': 'Champion',
  'gaogamon': 'Champion',
  'garurumon': 'Champion',
  'gekomon': 'Champion',
  'geogreymon': 'Champion',
  'geremon': 'Champion',
  'gesomon': 'Champion',
  'golemon': 'Champion',
  'greymon': 'Champion',
  'grizzmon': 'Champion',
  'growlmon': 'Champion',
  'guardromon': 'Champion',
  'gwappamon': 'Champion',
  'hookmon': 'Champion',
  'hyogamon': 'Champion',
  'icedevimon': 'Champion',
  'icemon': 'Champion',
  'igamon': 'Champion',
  'ikkakumon': 'Champion',
  'j-mojyamon': 'Champion',
  'kabuterimon': 'Champion',
  'karatsukinumemon': 'Champion',
  'kiwimon': 'Champion',
  'knightchessmonblack': 'Champion',
  'knightchessmonwhite': 'Champion',
  'kokatorimon': 'Champion',
  'kougamon': 'Champion',
  'kuwagamon': 'Champion',
  'kyubimon': 'Champion',
  'lekismon': 'Champion',
  'leomon': 'Champion',
  'leppamon': 'Champion',
  'mechanorimon': 'Champion',
  'minotarumon': 'Champion',
  'mojyamon': 'Champion',
  'monochromon': 'Champion',
  'morishellmon': 'Champion',
  'mudfrigimon': 'Champion',
  'musyamon': 'Champion',
  'nanimon': 'Champion',
  'nisedrimogemon': 'Champion',
  'numemon': 'Champion',
  'octomon': 'Champion',
  'ogremon': 'Champion',
  'omekamon': 'Champion',
  'peckmon': 'Champion',
  'platinumsukamon': 'Champion',
  'raptordramon': 'Champion',
  'raremon': 'Champion',
  'redveggiemon': 'Champion',
  'roachmon': 'Champion',
  'saberdramon': 'Champion',
  'sandyanmamon': 'Champion',
  'sangloupmon': 'Champion',
  'seadramon': 'Champion',
  'seasarmon': 'Champion',
  'shellmon': 'Champion',
  'snimon': 'Champion',
  'sorcerymon': 'Champion',
  'starmon': 'Champion',
  'stingmon': 'Champion',
  'sukamon': 'Champion',
  'sunflowmon': 'Champion',
  'tailmon': 'Champion',
  'tankmon': 'Champion',
  'thundermon': 'Champion',
  'togemon': 'Champion',
  'tortomon': 'Champion',
  'tyranomon': 'Champion',
  'unimon': 'Champion',
  'v-dramon': 'Champion',
  'veggiemon': 'Champion',
  'weedmon': 'Champion',
  'wendimon': 'Champion',
  'wizarmon': 'Champion',
  'woodmon': 'Champion',
  'xv-mon': 'Champion',
  'yanmamon': 'Champion',

  // Ultimate (Perfect)
  'aeroveedramon': 'Ultimate',
  'allomon': 'Ultimate',
  'alturkabuterimonred': 'Ultimate',
  'andromon': 'Ultimate',
  'angewomon': 'Ultimate',
  'antiramon': 'Ultimate',
  'arachnemon': 'Ultimate',
  'argomonperfect': 'Ultimate',
  'bigmamemon': 'Ultimate',
  'bishopchessmon': 'Ultimate',
  'blackrapidmon': 'Ultimate',
  'blackwargrowlmon': 'Ultimate',
  'blossomon': 'Ultimate',
  'brachiomon': 'Ultimate',
  'cherrymon': 'Ultimate',
  'crescemon': 'Ultimate',
  'cyberdramon': 'Ultimate',
  'deramon': 'Ultimate',
  'digitamamon': 'Ultimate',
  'dinobeemon': 'Ultimate',
  'divermon': 'Ultimate',
  'dorugreymon': 'Ultimate',
  'dragomon': 'Ultimate',
  'etemon': 'Ultimate',
  'flamedramon': 'Ultimate',
  'flaremon': 'Ultimate',
  'garbagemon': 'Ultimate',
  'garudamon': 'Ultimate',
  'gigadramon': 'Ultimate',
  'giromon': 'Ultimate',
  'grappleomon': 'Ultimate',
  'holyangemon': 'Ultimate',
  'infermon': 'Ultimate',
  'kabukimon': 'Ultimate',
  'karatenmon': 'Ultimate',
  'kenkimon': 'Ultimate',
  'knightmon': 'Ultimate',
  'kongoumon': 'Ultimate',
  'kyukimon': 'Ultimate',
  'ladydevimon': 'Ultimate',
  'lilamon': 'Ultimate',
  'lilymon': 'Ultimate',
  'lucemonfdm': 'Ultimate',
  'lynxmon': 'Ultimate',
  'machgaogamon': 'Ultimate',
  'magnamon': 'Ultimate',
  'mamemon': 'Ultimate',
  'mametyramon': 'Ultimate',
  'mammothmon': 'Ultimate',
  'marinedevimon': 'Ultimate',
  'matadormon': 'Ultimate',
  'megadramon': 'Ultimate',
  'megakabuterimonblue': 'Ultimate',
  'megaseadramon': 'Ultimate',
  'metalgreymon': 'Ultimate',
  'metalmamemon': 'Ultimate',
  'metaltyrannomon': 'Ultimate',
  'meteormon': 'Ultimate',
  'monzaemon': 'Ultimate',
  'mummymon': 'Ultimate',
  'nanomon': 'Ultimate',
  'okuwamon': 'Ultimate',
  'owlmon': 'Ultimate',
  'paildramon': 'Ultimate',
  'pandamon': 'Ultimate',
  'parrotmon': 'Ultimate',
  'phantomon': 'Ultimate',
  'pipismon': 'Ultimate',
  'piximon': 'Ultimate',
  'ponchomon': 'Ultimate',
  'prariemon': 'Ultimate',
  'qilinmon': 'Ultimate',
  'rapidmon': 'Ultimate',
  'rizegreymon': 'Ultimate',
  'rookchessmon': 'Ultimate',
  'scorpiomon': 'Ultimate',
  'seahomon': 'Ultimate',
  'shadramon': 'Ultimate',
  'shakkoumon': 'Ultimate',
  'shaujingmon': 'Ultimate',
  'shogungekomon': 'Ultimate',
  'shurimon': 'Ultimate',
  'silphymon': 'Ultimate',
  'sinduramon': 'Ultimate',
  'skullgreymon': 'Ultimate',
  'superstarmon': 'Ultimate',
  'taomon': 'Ultimate',
  'tekkamon': 'Ultimate',
  'toucanmon': 'Ultimate',
  'triceramon': 'Ultimate',
  'tylomon': 'Ultimate',
  'vademon': 'Ultimate',
  'vajramon': 'Ultimate',
  'vamdemon': 'Ultimate',
  'vermilimon': 'Ultimate',
  'volcamon': 'Ultimate',
  'wargrowlmon': 'Ultimate',
  'weregarurumon': 'Ultimate',
  'weregarurumonblack': 'Ultimate',
  'whamon': 'Ultimate',
  'xtyrannomon': 'Ultimate',
  'yatagaramon': 'Ultimate',
  'zudomon': 'Ultimate',

  // Mega (Ultimate)
  'alphamon': 'Mega',
  'anubismon': 'Mega',
  'apocalymon': 'Mega',
  'apollomon': 'Mega',
  'argomonultimate': 'Mega',
  'armageddemon': 'Mega',
  'babamon': 'Mega',
  'baihumon': 'Mega',
  'bantyoleomon': 'Mega',
  'barbamon': 'Mega',
  'beelzebumon': 'Mega',
  'beelzebumonblaster': 'Mega',
  'belialvamdemon': 'Mega',
  'belphemon': 'Mega',
  'blacksaintgalgomon': 'Mega',
  'blackwargreymon': 'Mega',
  'boltmon': 'Mega',
  'cannondramon': 'Mega',
  'chaosdukemon': 'Mega',
  'chaosdukemoncore': 'Mega',
  'chaosgrimmon': 'Mega',
  'chaosmon': 'Mega',
  'cherubimon': 'Mega',
  'cherubimonvirus': 'Mega',
  'chronomon': 'Mega',
  'chronomondm': 'Mega',
  'creepymon': 'Mega',
  'daemon': 'Mega',
  'darkdramon': 'Mega',
  'deathmon': 'Mega',
  'deathmonblack': 'Mega',
  'devitamamon': 'Mega',
  'diaboromon': 'Mega',
  'dianamon': 'Mega',
  'dorugoramon': 'Mega',
  'duftmon': 'Mega',
  'dukemon': 'Mega',
  'dukemoncm': 'Mega',
  'eaglemon': 'Mega',
  'ebemon': 'Mega',
  'exogrimmon': 'Mega',
  'gaiomon': 'Mega',
  'galfmon': 'Mega',
  'gigaseadramon': 'Mega',
  'goldramon': 'Mega',
  'grandracmon': 'Mega',
  'grankuwagamon': 'Mega',
  'granlocomon': 'Mega',
  'grimmon': 'Mega',
  'gryphonmon': 'Mega',
  'herculeskabuterimon': 'Mega',
  'hiandromon': 'Mega',
  'imperialdramon': 'Mega',
  'imperialdramondmblack': 'Mega',
  'imperialdramonfighter': 'Mega',
  'imperialdramonpaladin': 'Mega',
  'jijimon': 'Mega',
  'jumbogamemon': 'Mega',
  'justimon': 'Mega',
  'kingchessmon': 'Mega',
  'kuzuhamon': 'Mega',
  'lampmon': 'Mega',
  'leviamon': 'Mega',
  'lilithmon': 'Mega',
  'lotusmon': 'Mega',
  'machinedramon': 'Mega',
  'magnadramon': 'Mega',
  'marineangemon': 'Mega',
  'megidramon': 'Mega',
  'merukimon': 'Mega',
  'metaletemon': 'Mega',
  'metalgarurumon': 'Mega',
  'metalseadramon': 'Mega',
  'milleniummon': 'Mega',
  'minervamon': 'Mega',
  'miragegaogamon': 'Mega',
  'miragegaogamonburst': 'Mega',
  'moonmilleniummon': 'Mega',
  'neptunmon': 'Mega',
  'omegamon': 'Mega',
  'ophanimon': 'Mega',
  'ophanimoncore': 'Mega',
  'parasimon': 'Mega',
  'pharaohmon': 'Mega',
  'phoenixmon': 'Mega',
  'piedmon': 'Mega',
  'plesiomon': 'Mega',
  'princemamemon': 'Mega',
  'pukumon': 'Mega',
  'puppetmon': 'Mega',
  'queenchessmon': 'Mega',
  'quinglongmon': 'Mega',
  'ravemon': 'Mega',
  'ravemonburst': 'Mega',
  'rosemon': 'Mega',
  'rosemonburst': 'Mega',
  'saberleomon': 'Mega',
  'saintgalgomon': 'Mega',
  'sakuyamon': 'Mega',
  'seraphimon': 'Mega',
  'shinegreymon': 'Mega',
  'shinegreymonburst': 'Mega',
  'shinegreymonruin': 'Mega',
  'skullbarukimon': 'Mega',
  'skullmammon': 'Mega',
  'slashangemon': 'Mega',
  'sleipmon': 'Mega',
  'spinomon': 'Mega',
  'susanoomon': 'Mega',
  'valkyrimon': 'Mega',
  'varodurumon': 'Mega',
  'venommyotismon': 'Mega',
  'vikemon': 'Mega',
  'wargreymon': 'Mega',
  'waruseadramon': 'Mega',
  'xuanwumon': 'Mega',
  'zanbamon': 'Mega',
  'zeedmillenniummon': 'Mega',
  'zhuqiaomon': 'Mega',

  // Additions (mixed stages)
  'aegisdramon': 'Mega',
  'bastemon': 'Ultimate',
  'beelzemonxros': 'Mega',
  'blastmon': 'Ultimate',
  'bluemeramon': 'Champion',
  'bommon': 'Baby',
  'cerberumon': 'Ultimate',
  'chaosdramon': 'Mega',
  'daipenmon': 'Mega',
  'dondokomon': 'Rookie',
  'gaossmon': 'Rookie',
  'greymonxw': 'Champion',
  'lucemon': 'Rookie',
  'madleomon': 'Ultimate',
  'nefertimon': 'Champion',
  'shoutmonb': 'Champion',
  'skullscorpiomon': 'Ultimate',
  'tactimon': 'Mega',
};

// Build reverse lookup: given a digimon, what can it evolve FROM?
const DEVOLVES_FROM = {};
for (const [from, toList] of Object.entries(DIGIVOLUTION_CHAINS)) {
  for (const to of toList) {
    if (!DEVOLVES_FROM[to]) DEVOLVES_FROM[to] = [];
    DEVOLVES_FROM[to].push(from);
  }
}

/**
 * Get possible digivolutions for a Digimon
 * @param {string} name - Digimon name (case-insensitive)
 * @returns {string[]} Array of possible digivolution names
 */
function getDigivolutions(name) {
  return DIGIVOLUTION_CHAINS[(name || '').toLowerCase()] || [];
}

/**
 * Get what this Digimon can devolve from
 * @param {string} name - Digimon name (case-insensitive)
 * @returns {string[]} Array of previous forms
 */
function getPreviousForms(name) {
  return DEVOLVES_FROM[(name || '').toLowerCase()] || [];
}

/**
 * Get stage name for a Digimon
 * @param {string} name - Digimon name (case-insensitive)
 * @returns {string} Stage name (Baby, Rookie, Champion, Ultimate, Mega)
 */
function getStage(name) {
  return STAGE_ORDER[(name || '').toLowerCase()] || 'Unknown';
}

module.exports = { DIGIVOLUTION_CHAINS, STAGE_ORDER, DEVOLVES_FROM, getDigivolutions, getPreviousForms, getStage };
